### PR TITLE
fix: script dir independent of git

### LINKED ISSUE #20: deploy scripts must not use git commands
These scripts will most likely be used from release as a source.tar.gz, so using git command will throw error `fatal: not a git repository `

https://github.com/SUSE/minibroker-integration-tests/blob/e0a564a7d25b3249972b819601e6476b4157bfee/deploy/minibroker.sh#L33

### PR DESCRIPTION
**Pull request by f0rmiga**
Using dirname, realpath and BASH_SOURCE allows the script to be called without relying on the project being a git repository. This is useful for calling the script using the release tarball.

### CODE REVIEW

File: deploy/minibroker.sh [hunk 1]
```diff
@@ -30,7 +30,7 @@ if ! helm version 1> /dev/null 2> /dev/null; then
   exit 1
 fi
 
-git_root="$(git rev-parse --show-toplevel)"
+script_dir="$(dirname "$(realpath "${BASH_SOURCE}")")"
```
Comment (mook-as) [inline deploy/minibroker.sh:33]: I think you technically want `${BASH_SOURCE[0]}` but `${BASH_SOURCE}` implicitly means the first one?
(I don't think `realpath` is going to be on macOS, but we probably don't care.)

**Review by mook-as — APPROVED** [review]
I assume we also want to do this to all the other scripts in `build/` too?

File: deploy/minibroker.sh (hunk 1 above)
Comment (f0rmiga) [reply deploy/minibroker.sh:33]: I slightly care... but macOS users can install `coreutils` using Homebrew.

**Comment by f0rmiga** [comment]
@mook-as Not if it's not totally necessary. As soon as we start using this pattern everywhere, it becomes a mess when moving scripts around due to the relative paths.
